services:
  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - "6379:6379"

  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: teste
      POSTGRES_PASSWORD: teste
      POSTGRES_DB: checkins
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: